<ul class="menu">
	<li><a class="button" href="tool.php">Search</a></li>
	<li><a class="button" href="tool.php?list">List</a></li>
	<li><a class="button" href="tool.php?save">Save</a></li>
	<li><a class="button" href="tool.php?stat">Stats</a></li>
	<li><a class="button" href="tool.php?chart=byYear">Charts</a></li>
	<li><a class="button" href="tool.php?chart=byCateg">Scatter</a></li>
	<li><a class="button" href="tool.php?chart=SQLScatter">SQLScatter</a></li>
</ul>
