<!doctype html>
<html>
  <head>
		<link href="css/tool.css" rel="stylesheet" type="text/css" />
    <script	src="js/jquery-3.1.0.min.js" ></script>
		<script type="text/javascript" src="js/underscore-min.js"></script>
		<script src="js/d3.v4.js"></script>
    <script src="js/downloadsvg.js" charset="utf-8"></script>

<style>
  h1 {margin-bottom:3em;}
</style>
	</head>
<body>
<?php include "tool_menu.phtml";?>
<form type="get">
<select name="chart">
  <option>byCateg</option>
  <option>byYear</option>
</select>
<select name="cat1">
  <?php foreach($categories as $c) echo "<option".(($c==$cat1)?" selected":"").">$c</option>" ?>
</select>
<select name="cat2">
  <?php foreach($categories as $c) echo "<option".(($c==$cat2)?" selected":"").">$c</option>" ?>
</select>
<input type="submit" value="ok"/>
</form>

<h1><?=$chart?>: <?=$cat1?>/<?=$cat2?></h1>
<div class="chart" id="chart"></div>

<script>


var text = d3.select('.chart');

var c1 = '<?=$cat1?>';
var c2 = '<?=$cat2?>';
  
function svgMove(list,x,y) {
  list.attr("transform", "translate(" + x + "," + y + ")");
}

d3.json('tool.php?json=byCateg&cat1='+c1+'&cat2='+c2, function(error,data) {
	
  if(error) return console.log(error);
  
  var margin = {};
  margin.left = 120;
  margin.bottom = 80;

  var width = 600
    , height = 600
    , getCategory = (d,i) => i      // maps data to category
    , getValue = (d) => d           // maps data to value
    , colors = d3.schemeCategory20
  ;

  var xcat = data.values1
    , ycat = data.values2
    , nums = data.data
  ; 

  var sizeScale = d3.scaleLinear()
                  .domain([0, d3.max(nums,(n)=>Math.sqrt(n.db))])
                  .range([0,20])
    , xScale = d3.scalePoint()
        .domain(xcat)
        .range([0, width - margin.left])
        .padding(0.7)
    , yScale = d3.scalePoint()
        .domain(ycat)
        .range([0, height - margin.bottom])
        .padding(0.7)
  ;

  var getNum = (d) => sizeScale(Math.sqrt(d.db))
    , getX = (d) => xScale(d.val1)
    , getY = (d) => yScale(d.val2)
  ;

  console.log(data);
  console.log(getNum(data.data[1]));

  var xAxis = d3.axisBottom().scale(xScale);
  var yAxis = d3.axisLeft().scale(yScale);
  
	var chart = d3.select('div.chart')
    .append('svg')
      .style('width',width + "px")
      .style('height',height+ "px")
  ;

  chart.append('g')
      .classed('axis',true)
    .call(yAxis)
      .call(svgMove,margin.left,0);
  chart.append('g')
      .classed('axis',true)
      .call(xAxis)
        .call(svgMove,margin.left,height-margin.bottom)
      .selectAll('text')
        .attr('y', '0')
        .attr('x', '8')
        .attr('text-anchor', 'start')
        .attr('transform', 'rotate(60)')
   ;

  var circles = chart
    .append('g')
      .classed('chartarea',true)
      .call(svgMove, margin.left, 0)
    .selectAll('circle')
    .data(nums)
    .enter();

  circles.append('circle')
      .attr('r', getNum)
      .attr('cx', getX)
      .attr('cy', getY)
      .style('fill', 'white')
      .style('stroke', 'black')
      .style('stroke-width', '1')
     ;

  circles.append('text')
    .text((d)=>d.db)
    .attr('x',getX)
    .attr('y',(d) => getY(d) + 3 )
    .style('text-anchor', 'middle')
    .style('font-size', '8pt')
    .style('display', (d) => {if (d.db<8) return "none" ; else return "block";})
});

$(function(){
  setTimeout(function(){
    encode_as_img_and_link("#chart svg");
  }, 1000);
});

</script>
</body>
</html>
<?php # vim: set ts=2 sw=2 et :
